const OBTER_PROJETOS = 'OBTER_PROJETOS';
const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO';
const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
const REMOVER_PROJETO = 'REMOVER_PROJETO';

export { OBTER_PROJETOS, CADASTRAR_PROJETO, ALTERAR_PROJETO, REMOVER_PROJETO };