const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
const ALTERA_PROJETO = 'ALTERA_PROJETO'
const EXCLUI_PROJETO = 'EXCLUI_PROJETO'
const NOTIFICAR = 'NOTIFICAR'

export { ADICIONA_PROJETO, ALTERA_PROJETO, EXCLUI_PROJETO, NOTIFICAR }