const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
const ALTERA_PROJETO = 'ALTERA_PROJETO'
const EXCLUI_PROJETO = 'EXCLUI_PROJETO'
const NOTIFICAR = 'NOTIFICAR'
const DEFINR_PROJETOS = 'DEFINIR_PROJETOS'

export { ADICIONA_PROJETO, ALTERA_PROJETO, EXCLUI_PROJETO, NOTIFICAR, DEFINR_PROJETOS }